# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2021-10-15 22:48+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"

#: app/access_control/access_policy.py:87
msgid "Namespace in filename not found."
msgstr "未找到文件名中的命名空间。"

#: app/access_control/fields.py:17
msgid "object_permissions field is required"
msgstr "object_permissions 字段是必需的"

#: app/access_control/fields.py:21
msgid "id or name field is required"
msgstr "id 或 name 字段是必需的"

#: app/access_control/fields.py:27
msgid "object_permissions must be a list of strings"
msgstr "object_permissions 必须是一个字符串列表"

#: app/access_control/fields.py:41
msgid "Permission {} does not exist"
msgstr "权限 {} 不存在"

#: app/access_control/fields.py:56
msgid "Groups must be a list of group objects"
msgstr "组必须是一个组对象的列表"

#: app/access_control/fields.py:71
#, python-format
msgid "Group name=%s, id=%s does not exist"
msgstr "组名=%s，id=%s 不存在"

#: app/access_control/fields.py:75 app/api/ui/serializers/user.py:132
msgid "Invalid group name or ID"
msgstr "无效的组名称或 ID。"

#: app/api/ui/serializers/execution_environment.py:375
#| msgid "Namespace \"{0}\" does not exist."
msgid "Selected registry does not exist."
msgstr "所选 registry 不存在。"

#: app/api/ui/serializers/execution_environment.py:384
msgid ""
"Container names can only contain alphanumeric numbers, \".\", \"_\", \"-\" "
"and a up to one \"/\"."
msgstr "容器名称只能包含字母数字，\".\"、\"_\"、\"-\"，以及最多一个 \"/\"。"

#: app/api/ui/serializers/execution_environment.py:402
#| msgid "Name cannot begin with '_'"
msgid "Name cannot be changed."
msgstr "名称不能更改。"

#: app/api/ui/serializers/synclist.py:41
#, python-brace-format
msgid "Repository \"{pulp_id}\" not found while creating synclist"
msgstr "创建同步列表时未找到存储库 \"{pulp_id}\""

#: app/api/ui/serializers/synclist.py:96
#, python-format
msgid "Synclist already exists: %s"
msgstr "同步类别已存在：%s"

#: app/api/ui/serializers/synclist.py:104
#, python-brace-format
msgid ""
"Collection \"{namespace}.{name}\" not found while creating synclist "
"{synclist}"
msgstr "创建同步列表 {synclist} 时找不到集合 \"{namespace}.{name}\""

#: app/api/ui/serializers/synclist.py:143
#, python-brace-format
msgid ""
"Collection \"{namespace}.{name}\" not found while updating synclist "
"{synclist}"
msgstr "更新同步列表 {synclist} 时找不到集合 \"{namespace}.{name}\""

#: app/api/ui/serializers/user.py:74
msgid ""
"'galaxy.change_group' permission is required to change a users group that "
"the requesting user is not in."
msgstr "更改请求用户不在的用户组需要具有 'galaxy.change_group' 权限。"

#: app/api/ui/serializers/user.py:85
msgid "Must be a super user to grant super user permissions."
msgstr "必须是超级用户才能授予超级用户权限。"

#: app/api/ui/serializers/user.py:128
#, python-format
msgid "Group name=%(name)s, id=%(id)s does not exist"
msgstr "组 name=%(name)s, id=%(id)s 不存在"

#: app/api/ui/views/index_execution_environments.py:36
msgid "Indexing execution environments is not supported on this registry."
msgstr "此 registry 不支持索引执行环境。"

#: app/api/ui/views/sync.py:37 app/api/v3/views/sync.py:34
#, python-format
msgid "The %s distribution does not have any remotes associated with it."
msgstr "%s 发行版没有任何与之关联的远程设备。"

#: app/api/ui/views/sync.py:51
#, python-format
#| msgid "The %s distribution does not have any remotes associated with it."
msgid "The %s remote does not have any registries associated with it."
msgstr "%s 远程没有任何 registry 与之关联。"

#: app/api/ui/viewsets/collection.py:60
msgid "Distribution base path is required"
msgstr "发布基础路径是必需的"

#: app/api/ui/viewsets/collection.py:175
msgid "Retrieve collection version"
msgstr "检索集合版本"

#: app/api/ui/viewsets/collection.py:186
msgid "Collection version not found for: {}"
msgstr "未找到集合版本：{}"

#: app/api/ui/viewsets/collection.py:242
msgid "Retrieve collection import"
msgstr "检索集合导入"

#: app/api/ui/viewsets/group.py:45
#, python-format
msgid "A group named %s already exists."
msgstr "名为 %s 的组已存在。"

#: app/api/utils.py:49
#, python-brace-format
msgid ""
"Invalid filename {filename}. Expected format: namespace-name-version.tar.gz"
msgstr "无效的文件名 {filename}。预期的格式：namespace-name-version.tar.gz"

#: app/api/utils.py:56
#, python-brace-format
msgid ""
"Invalid version string {version} from filename {filename}. Expected semantic "
"version format."
msgstr "文件名 {filename} 中的无效版本字符串 {version}。预期语义版本格式。"

#: app/api/utils.py:60
#, python-format
msgid "Expected namespace to be max length of %s"
msgstr "预期命名空间最大长度为 %s"

#: app/api/utils.py:62
#, python-format
msgid "Expected name to be max length of %s"
msgstr "预期名称最大长度为 %s"

#: app/api/utils.py:64
#, python-format
msgid "Expected version to be max length of %s"
msgstr "预期版本的最大长度为 %s"

#: app/api/v3/serializers/namespace.py:60
#, python-format
msgid "'%s' is not a valid url."
msgstr "'%s' 不是一个有效字符串。"

#: app/api/v3/serializers/namespace.py:88
msgid "Attribute 'name' is required"
msgstr "需要 'name' 属性"

#: app/api/v3/serializers/namespace.py:91
msgid "Name can only contain lower case letters, underscores and numbers"
msgstr "名称只能包含小写字母、下划线和数字"

#: app/api/v3/serializers/namespace.py:94
msgid "Name must be longer than 2 characters"
msgstr "名称必须大于 2 个字符"

#: app/api/v3/serializers/namespace.py:97
msgid "Name cannot begin with '_'"
msgstr "名称不能以 '_' 开头."

#: app/api/v3/serializers/sync.py:66
msgid "Password for proxy authentication."
msgstr "用于代理身份验证的密码。"

#: app/api/v3/serializers/sync.py:73
msgid "User for proxy authentication."
msgstr "用于代理身份验证的用户。"

#: app/api/v3/serializers/sync.py:86
msgid "Remote password."
msgstr "远程密码。"

#: app/api/v3/serializers/sync.py:93
msgid "Remote user."
msgstr "远程用户。"

#: app/api/v3/serializers/sync.py:146
msgid ""
"Syncing content from community domains without specifying a requirements "
"file is not allowed."
msgstr "不允许从社区域同步内容而不指定要求文件。"

#: app/api/v3/views/sync.py:45
msgid ""
"Syncing content from galaxy.ansible.com without specifying a requirements "
"file is not allowed."
msgstr "在不指定要求文件的情况下，不允许从 galaxy.ansible.com 同步内容。"

#: app/api/v3/viewsets/collection.py:122
#, python-brace-format
msgid ""
"Collection {namespace}.{name} could not be deleted because there are other "
"collections that require it."
msgstr "集合 {namespace}.{name} 无法被删除，因为还有其他集合需要它。"

#: app/api/v3/viewsets/collection.py:200
#, python-brace-format
msgid ""
"Collection version {namespace}.{name} {version} could not be deleted because "
"there are other collections that require it."
msgstr "集合版本 {namespace}.{name} {version} 无法被删除，因为还有其他集合需要它。"

#: app/api/v3/viewsets/collection.py:289
#, python-format
msgid "Path does not match: \"%s\""
msgstr "路径不匹配：\"%s\""

#: app/api/v3/viewsets/collection.py:310
#, python-brace-format
msgid "Namespace \"{0}\" does not exist."
msgstr "命名空间 \"{0}\" 不存在。"

#: app/api/v3/viewsets/collection.py:398
#, python-format
msgid "Unexpected response from content app. Code: %s."
msgstr "来自内容应用的意外响应。代码：%s。"

#: app/api/v3/viewsets/collection.py:428
#, python-format
msgid "Collection %s not found"
msgstr "未找到集合 %s"

#: app/api/v3/viewsets/collection.py:436
#, python-format
msgid "Repo(s) for moving collection %s not found"
msgstr "未找到用于移动集合的存储库 %s"

#: app/api/v3/viewsets/collection.py:440
#, python-format
msgid "Collection %s not found in source repo"
msgstr "源仓库中没有找到集合 %s"

#: app/api/v3/viewsets/collection.py:444
#, python-format
msgid "Collection %s already found in destination repo"
msgstr "目标仓库中已找到集合 %s"

#: app/api/v3/viewsets/namespace.py:67
#, python-format
msgid "A namespace named %s already exists."
msgstr "已存在名为 %s 的命名空间。"

#: app/api/v3/viewsets/namespace.py:88
#, python-brace-format
msgid ""
"Namespace {name} cannot be deleted because there are still collections "
"associated with it."
msgstr "命名空间 {name} 无法被删除，因为仍存在与其关联的集合。"

#: app/auth/keycloak.py:51
msgid "Authentication failed."
msgstr "认证失败。"

#: app/exceptions.py:8
msgid "Data conflicts with existing entity."
msgstr "数据与现有实体冲突。"

#: app/tasks/index_registry.py:26
#, python-brace-format
msgid "Failed to create container {remote_name}. {error}"
msgstr "创建容器 {remote_name} 失败。{error}"

#: app/tasks/index_registry.py:90
msgid ""
"A remote container with this name already exists, but is not associated with "
"any registry."
msgstr "具有此名称的远程容器已存在，但不与任何 registry 关联。"

#: app/tasks/index_registry.py:97
#| msgid "A namespace named %s already exists."
msgid "A local container with this name already exists."
msgstr "具有此名称的本地容器已经存在。"

#: app/tasks/publishing.py:54 app/tasks/publishing.py:84
#, python-format
msgid "Could not find staging repository: \"%s\""
msgstr "无法找到 staging存储库：\"%s\""

#: app/tasks/synclist.py:45
#, python-format
msgid "Curating all synclists repos that curate from %s"
msgstr "策展从 %s 中策展的所有同步列表"

#: app/tasks/synclist.py:56
msgid "Synclists curating upstream repo"
msgstr "Synclists 策展上游存储库"

#: app/tasks/synclist.py:63
msgid "Synclists curating upstream repo task"
msgstr "Synclists 策展上游存储库任务"

#: app/tasks/synclist.py:91
#, python-format
msgid "Finishing curating %s synclist repos based on %s update"
msgstr "根据 %s 更新完成策展 %s 同步列表存储库"

#: app/tasks/synclist.py:120
#, python-format
msgid ""
"Applying synclist \"%s\" with policy=%s to curate repo \"%s\" from upstream "
"repo \"%s\""
msgstr "使用 policy=%s 应用同步列表 \"%s\" 以从上游仓库 \"%s\" 中策展存储库 \"%s\""

#: app/tasks/synclist.py:162
msgid "Unexpected synclist policy {}"
msgstr "意外同步列表策略 {}"
