
# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2022-02-17 04:14+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: es\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"

#: app/access_control/access_policy.py:87
msgid "Namespace in filename not found."
msgstr "No se ha encontrado el espacio de nombres en el nombre del archivo."

#: app/access_control/fields.py:17
msgid "object_permissions field is required"
msgstr "el campo object_permissions es obligatorio"

#: app/access_control/fields.py:21
msgid "id or name field is required"
msgstr "el campo id o nombre es obligatorio"

#: app/access_control/fields.py:27
msgid "object_permissions must be a list of strings"
msgstr "object_permissions debe ser una lista de cadenas"

#: app/access_control/fields.py:41
msgid "Permission {} does not exist"
msgstr "El permiso {} no existe"

#: app/access_control/fields.py:56
msgid "Groups must be a list of group objects"
msgstr "Los grupos deben ser una lista de objetos de grupo"

#: app/access_control/fields.py:71
#, python-format
msgid "Group name=%s, id=%s does not exist"
msgstr "El grupo name=%s, id=%s no existe"

#: app/access_control/fields.py:75 app/api/ui/serializers/user.py:132
msgid "Invalid group name or ID"
msgstr "Nombre o ID de grupo no válido"

#: app/api/ui/serializers/execution_environment.py:375
msgid "Selected registry does not exist."
msgstr "El registro seleccionado no existe."

#: app/api/ui/serializers/execution_environment.py:384
msgid ""
"Container names can only contain alphanumeric numbers, \".\", \"_\", \"-\" "
"and a up to one \"/\"."
msgstr "Los nombres de los contenedores sólo pueden contener números alfanuméricos, \".\", \"_\", \"-\" y un máximo de un \"/\"."

#: app/api/ui/serializers/execution_environment.py:402
msgid "Name cannot be changed."
msgstr "El nombre no se puede cambiar."

#: app/api/ui/serializers/synclist.py:41
#, python-brace-format
msgid "Repository \"{pulp_id}\" not found while creating synclist"
msgstr "No se encontró el repositorio \"{pulp_id}\" al crear la lista de sincronización"

#: app/api/ui/serializers/synclist.py:96
#, python-format
msgid "Synclist already exists: %s"
msgstr "La lista de sincronización ya existe: %s"

#: app/api/ui/serializers/synclist.py:104
#, python-brace-format
msgid ""
"Collection \"{namespace}.{name}\" not found while creating synclist "
"{synclist}"
msgstr "No se encontró la colección \"{namespace}.{name}\" al crear la lista de sincronización {synclist}"

#: app/api/ui/serializers/synclist.py:143
#, python-brace-format
msgid ""
"Collection \"{namespace}.{name}\" not found while updating synclist "
"{synclist}"
msgstr "No se encontró la colección \"{namespace}.{name}\" al actualizar la lista de sincronización {synclist}"

#: app/api/ui/serializers/user.py:74
msgid ""
"'galaxy.change_group' permission is required to change a users group that "
"the requesting user is not in."
msgstr "El permiso 'galaxy.change_group' es necesario para cambiar un grupo de usuarios en el que el usuario solicitante no está."

#: app/api/ui/serializers/user.py:85
msgid "Must be a super user to grant super user permissions."
msgstr "Debe ser un superusuario para conceder permisos de superusuario."

#: app/api/ui/serializers/user.py:128
#, python-format
msgid "Group name=%(name)s, id=%(id)s does not exist"
msgstr "El grupo name=%(name)s, id=%(id)s no existe"

#: app/api/ui/views/index_execution_environments.py:36
msgid "Indexing execution environments is not supported on this registry."
msgstr "La indexación de entornos de ejecución no es compatible con este registro."

#: app/api/ui/views/sync.py:37 app/api/v3/views/sync.py:34
#, python-format
msgid "The %s distribution does not have any remotes associated with it."
msgstr "La distribución %s no tiene ningún mando a distancia asociado."

#: app/api/ui/views/sync.py:51
#, python-format
msgid "The %s remote does not have any registries associated with it."
msgstr "El mando a distancia %s no tiene ningún registro asociado."

#: app/api/ui/viewsets/collection.py:60
msgid "Distribution base path is required"
msgstr "Se requiere una ruta base de distribución"

#: app/api/ui/viewsets/collection.py:175
msgid "Retrieve collection version"
msgstr "Recuperar la versión de la colección"

#: app/api/ui/viewsets/collection.py:186
msgid "Collection version not found for: {}"
msgstr "No se ha encontrado la versión de la colección para: {}"

#: app/api/ui/viewsets/collection.py:242
msgid "Retrieve collection import"
msgstr "Recuperación de la colección de importación"

#: app/api/ui/viewsets/group.py:45
#, python-format
msgid "A group named %s already exists."
msgstr "Ya existe un grupo llamado %s."

#: app/api/utils.py:49
#, python-brace-format
msgid ""
"Invalid filename {filename}. Expected format: namespace-name-version.tar.gz"
msgstr "Nombre de archivo no válido {filename}. Formato esperado: espacio de nombres-nombre-versión.tar.gz"

#: app/api/utils.py:56
#, python-brace-format
msgid ""
"Invalid version string {version} from filename {filename}. Expected semantic "
"version format."
msgstr "Cadena de versión no válida {version} de nombre de archivo {filename}. Se espera un formato de versión semántico."

#: app/api/utils.py:60
#, python-format
msgid "Expected namespace to be max length of %s"
msgstr "Se espera que el espacio de nombres tenga una longitud máxima de %s"

#: app/api/utils.py:62
#, python-format
msgid "Expected name to be max length of %s"
msgstr "Se espera que el nombre tenga una longitud máxima de %s"

#: app/api/utils.py:64
#, python-format
msgid "Expected version to be max length of %s"
msgstr "Se espera que la versión tenga una longitud máxima de %s"

#: app/api/v3/serializers/namespace.py:60
#, python-format
msgid "'%s' is not a valid url."
msgstr "'%s' no es una url válida."

#: app/api/v3/serializers/namespace.py:88
msgid "Attribute 'name' is required"
msgstr "El atributo \"nombre\" es obligatorio"

#: app/api/v3/serializers/namespace.py:91
msgid "Name can only contain lower case letters, underscores and numbers"
msgstr "El nombre sólo puede contener letras minúsculas, guiones bajos y números"

#: app/api/v3/serializers/namespace.py:94
msgid "Name must be longer than 2 characters"
msgstr "El nombre debe tener más de 2 caracteres"

#: app/api/v3/serializers/namespace.py:97
msgid "Name cannot begin with '_'"
msgstr "El nombre no puede empezar por \"_\""

#: app/api/v3/serializers/sync.py:66
msgid "Password for proxy authentication."
msgstr "Contraseña para la autenticación del proxy."

#: app/api/v3/serializers/sync.py:73
msgid "User for proxy authentication."
msgstr "Usuario para la autenticación del proxy."

#: app/api/v3/serializers/sync.py:86
msgid "Remote password."
msgstr "Contraseña remota."

#: app/api/v3/serializers/sync.py:93
msgid "Remote user."
msgstr "Usuario remoto."

#: app/api/v3/serializers/sync.py:146
msgid ""
"Syncing content from community domains without specifying a requirements "
"file is not allowed."
msgstr "No está permitido sincronizar contenidos de dominios comunitarios sin especificar un archivo de requisitos."

#: app/api/v3/views/sync.py:45
msgid ""
"Syncing content from galaxy.ansible.com without specifying a requirements "
"file is not allowed."
msgstr "No se permite sincronizar el contenido de galaxy.ansible.com sin especificar un archivo de requisitos."

#: app/api/v3/viewsets/collection.py:122
#, python-brace-format
msgid ""
"Collection {namespace}.{name} could not be deleted because there are other "
"collections that require it."
msgstr "No se pudo eliminar la colección {namespace}.{name} porque hay otras colecciones que la requieren."

#: app/api/v3/viewsets/collection.py:200
#, python-brace-format
msgid ""
"Collection version {namespace}.{name} {version} could not be deleted because "
"there are other collections that require it."
msgstr "No se pudo eliminar la colección versión {namespace}.{name} {version} porque hay otras colecciones que la requieren."

#: app/api/v3/viewsets/collection.py:292
#, python-format
msgid "Path does not match: \"%s\""
msgstr "La ruta no coincide: \"%s\""

#: app/api/v3/viewsets/collection.py:313
#, python-brace-format
msgid "Namespace \"{0}\" does not exist."
msgstr "El espacio de nombres \"{0}\" no existe."

#: app/api/v3/viewsets/collection.py:401
#, python-format
msgid "Unexpected response from content app. Code: %s."
msgstr "Respuesta inesperada de la aplicación de contenido. Código: %s."

#: app/api/v3/viewsets/collection.py:431
#, python-format
msgid "Collection %s not found"
msgstr "No se encontró la colección %s"

#: app/api/v3/viewsets/collection.py:439
#, python-format
msgid "Repo(s) for moving collection %s not found"
msgstr "No se encontraron los repositorios para mover la colección %s"

#: app/api/v3/viewsets/collection.py:443
#, python-format
msgid "Collection %s not found in source repo"
msgstr "No se encontró la colección %s en el repositorio de origen"

#: app/api/v3/viewsets/collection.py:447
#, python-format
msgid "Collection %s already found in destination repo"
msgstr "Ya se encontró la colección %s en el repositorio de destino"

#: app/api/v3/viewsets/namespace.py:67
#, python-format
msgid "A namespace named %s already exists."
msgstr "Ya existe un espacio de nombres llamado %s."

#: app/api/v3/viewsets/namespace.py:88
#, python-brace-format
msgid ""
"Namespace {name} cannot be deleted because there are still collections "
"associated with it."
msgstr "No se puede eliminar el espacio de nombres {name} porque todavía hay colecciones asociadas a él."

#: app/auth/keycloak.py:51
msgid "Authentication failed."
msgstr "La autenticación ha fallado."

#: app/exceptions.py:8
msgid "Data conflicts with existing entity."
msgstr "Los datos entran en conflicto con la entidad existente."

#: app/tasks/index_registry.py:26
#, python-brace-format
msgid "Failed to create container {remote_name}. {error}"
msgstr "Error al crear el contenedor {remote_name}. {error}"

#: app/tasks/index_registry.py:90
msgid ""
"A remote container with this name already exists, but is not associated with "
"any registry."
msgstr "Ya existe un contenedor remoto con este nombre, pero no está asociado a ningún registro."

#: app/tasks/index_registry.py:97
msgid "A local container with this name already exists."
msgstr "Ya existe un contenedor local con este nombre."

#: app/tasks/publishing.py:53 app/tasks/publishing.py:91
#, python-format
msgid "Could not find staging repository: \"%s\""
msgstr "No se pudo encontrar el repositorio de puesta en escena: \"%s\""

#: app/tasks/synclist.py:45
#, python-format
msgid "Curating all synclists repos that curate from %s"
msgstr "Curando todos los repositorios de listas de sincronización que curan de %s"

#: app/tasks/synclist.py:56
msgid "Synclists curating upstream repo"
msgstr "Listas de sincronización curando el repo del upstream"

#: app/tasks/synclist.py:63
msgid "Synclists curating upstream repo task"
msgstr "Tarea de curado de repo de listas de sincronización"

#: app/tasks/synclist.py:91
#, python-format
msgid "Finishing curating %s synclist repos based on %s update"
msgstr "Terminando de curar los repos de listas de sincronización %s basados en la actualización de %s"

#: app/tasks/synclist.py:120
#, python-format
msgid ""
"Applying synclist \"%s\" with policy=%s to curate repo \"%s\" from upstream "
"repo \"%s\""
msgstr "Aplicando lista de sincronización \"%s\" con policy=%s para curar el repositorio \"%s\" desde el repositorio \"%s\""

#: app/tasks/synclist.py:162
msgid "Unexpected synclist policy {}"
msgstr "Política de lista de sincronización inesperada {}"
