# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2022-10-28 11:07-0400\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"

#: app/access_control/access_policy.py:147
msgid "Namespace in filename not found."
msgstr "L'espace de nommage n'a pas été trouvé dans le nom de fichier."

#: app/access_control/access_policy.py:166
msgid "Namespace not found."
msgstr "Espace de nommage non trouvé."

#: app/access_control/fields.py:17
msgid "object_roles field is required"
msgstr "Le champ object_roles est obligatoire"

#: app/access_control/fields.py:21
msgid "id or name field is required"
msgstr "Le champ nom ou id est obligatoire."

#: app/access_control/fields.py:27
msgid "object_roles must be a list of strings"
msgstr "object_roles doit être une liste de chaînes de caractères"

#: app/access_control/fields.py:35
msgid "Role {} does not exist"
msgstr "Le rôle {} n'existe pas."

#: app/access_control/fields.py:50
msgid "Groups must be a list of group objects"
msgstr "Les groupes doivent correspondre à une liste d'objets de groupe"

#: app/access_control/fields.py:68
#, python-format
msgid "Group name=%s, id=%s does not exist"
msgstr "Le groupe nom=%s, id=%s n'existe pas"

#: app/access_control/fields.py:72 app/api/ui/serializers/user.py:156
msgid "Invalid group name or ID"
msgstr "Nom de groupe ou ID invalide"

#: app/access_control/mixins.py:55
#, python-brace-format
msgid ""
"Role {role} does not exist or does not have any permissions related to this "
"object."
msgstr "Le rôle {role} n'existe pas ou n'a pas de permissions liées à cet objet."

#: app/api/ui/serializers/execution_environment.py:379
msgid "Selected registry does not exist."
msgstr "Le registre sélectionné n'existe pas."

#: app/api/ui/serializers/execution_environment.py:388
msgid ""
"Container names can only contain alphanumeric numbers, \".\", \"_\", \"-\" "
"and a up to one \"/\"."
msgstr "Les noms de conteneurs ne peuvent contenir que des chiffres alphanumériques, \".\", \"_\", \"-\" et un maximum d'un \"/\"."

#: app/api/ui/serializers/execution_environment.py:406
msgid "Name cannot be changed."
msgstr "Le nom ne peut pas être modifié."

#: app/api/ui/serializers/synclist.py:38
#, python-brace-format
msgid "Repository \"{pulp_id}\" not found while creating synclist"
msgstr "Le référentiel \"{pulp_id}\" n'a pas été trouvé lors de la création de la synclist"

#: app/api/ui/serializers/synclist.py:65
#, python-format
msgid "Synclist already exists: %s"
msgstr "Synclist existe déjà : %s"

#: app/api/ui/serializers/synclist.py:73
#, python-brace-format
msgid ""
"Collection \"{namespace}.{name}\" not found while creating synclist "
"{synclist}"
msgstr "La collection \"{namespace}.{name}\" n'a pas été trouvée lors de la création de la synclist {synclist}"

#: app/api/ui/serializers/synclist.py:112
#, python-brace-format
msgid ""
"Collection \"{namespace}.{name}\" not found while updating synclist "
"{synclist}"
msgstr "La collection \"{namespace}.{name}\" n'a pas été trouvé lors de la mise à jour de la synclist {synclist}"

#: app/api/ui/serializers/user.py:74
msgid ""
"'galaxy.change_group' permission is required to change a users group that "
"the requesting user is not in."
msgstr "L'autorisation 'galaxy.change_group' est nécessaire pour modifier un groupe d'utilisateurs dont l'utilisateur demandeur ne fait pas partie."

#: app/api/ui/serializers/user.py:89 app/api/ui/serializers/user.py:95
msgid "Must be a super user to grant super user permissions."
msgstr "Il faut être un super utilisateur pour accorder des autorisations de super utilisateur."

#: app/api/ui/serializers/user.py:109
msgid "Must be a super user to change another user's password."
msgstr "Il faut être un super utilisateur pour changer le mot de passe d'un autre utilisateur."

#: app/api/ui/serializers/user.py:125
msgid "You do not have permissions to modify super users."
msgstr "Vous n'avez pas le droit de modifier les super utilisateurs."

#: app/api/ui/serializers/user.py:152
#, python-format
msgid "Group name=%(name)s, id=%(id)s does not exist"
msgstr "Le groupe nom=%(name)s, id=%(id)s n'existe pas"

#: app/api/ui/views/feature_flags.py:50
msgid ""
"WARNING:GALAXY_COLLECTION_SIGNING_SERVICE is set to '{}', however the "
"respective SigningService does not exist in the database."
msgstr "WARNING:GALAXY_COLLECTION_SIGNING_SERVICE a la valeur '{}', mais le service de signature correspondant n'existe pas dans la base de données."

#: app/api/ui/views/feature_flags.py:65
msgid ""
"WARNING:GALAXY_AUTO_SIGN_COLLECTIONS is set to True, however the system is "
"not configured with a SigningService to create signatures."
msgstr "WARNING:GALAXY_AUTO_SIGN_COLLECTIONS est défini sur True, mais le système n'est pas configuré avec un SigningService pour créer des signatures."

#: app/api/ui/views/feature_flags.py:76
msgid ""
"INFO:System is configured to display signatures (coming from remote syncs) "
"but is not configured to create or accept upload of signatures."
msgstr "INFO:Le système est configuré pour afficher les signatures (provenant de synchronisations à distance) mais n'est pas configuré pour créer ou accepter le téléchargement de signatures."

#: app/api/ui/views/feature_flags.py:93
msgid ""
"WARNING:GALAXY_CONTAINER_SIGNING_SERVICE is set to '{}', however the "
"respective SigningService does not exist in the database."
msgstr "WARNING:GALAXY_CONTAINER_SIGNING_SERVICE a pour valeur '{}', mais le SigningService correspondant n'existe pas dans la base de données."

#: app/api/ui/views/feature_flags.py:106
msgid ""
"WARNING: container_signing is enabled via '{}' SigningService, however "
"execution environments are disabled on the system."
msgstr "WARNING : container_signing est activé via '{}' SigningService, mais les environnements d'exécution sont désactivés sur le système."

#: app/api/ui/views/index_execution_environments.py:36
msgid "Indexing execution environments is not supported on this registry."
msgstr "L'indexation des environnements d'exécution n'est pas prise en charge par ce registre."

#: app/api/ui/views/signing.py:71
msgid "Missing required field: namespace"
msgstr "Champ obligatoire manquant"

#: app/api/ui/views/signing.py:88
#, python-format
msgid "No content units found for: %s"
msgstr "Aucun unité de contenu n’a été trouvée pour : %s"

#: app/api/ui/views/signing.py:103
msgid "distro_base_path field is required."
msgstr "Le champ distro_base_path est obligatoire."

#: app/api/ui/views/signing.py:108
#, python-format
msgid "Distribution %s does not exist."
msgstr "Distribution %s non existante"

#: app/api/ui/views/signing.py:114
msgid "signing_service field is required."
msgstr "Le champ signing_service est obligatoire"

#: app/api/ui/views/signing.py:117
#, python-format
msgid "Signing service \"%s\" does not exist."
msgstr "Le service de signature \"%s\" n’existe pas"

#: app/api/ui/views/sync.py:37 app/api/v3/views/sync.py:34
#, python-format
msgid "The %s distribution does not have any remotes associated with it."
msgstr "La distribution %s n'a pas d’utilisateurs distants associés."

#: app/api/ui/views/sync.py:51
#, python-format
msgid "The %s remote does not have any registries associated with it."
msgstr "La distribution %s n'a pas de registres associés."

#: app/api/ui/viewsets/collection.py:77
msgid "Distribution base path is required"
msgstr "Le chemin de la base de distribution est requis"

#: app/api/ui/viewsets/collection.py:221
msgid "Retrieve collection version"
msgstr "Récupérer la version de la collection"

#: app/api/ui/viewsets/collection.py:232
msgid "Collection version not found for: {}"
msgstr "Version de la collection non trouvée pour : {}"

#: app/api/ui/viewsets/collection.py:288
msgid "Retrieve collection import"
msgstr "Récupérer l'importation de la collection"

#: app/api/ui/viewsets/group.py:45
#, python-format
msgid "A group named %s already exists."
msgstr "Un groupe nommé %s existe déjà."

#: app/api/utils.py:49
#, python-brace-format
msgid ""
"Invalid filename {filename}. Expected format: namespace-name-version.tar.gz"
msgstr "Nom de fichier {filename} non valide. Format attendu : namespace-name-version.tar.gz"

#: app/api/utils.py:56
#, python-brace-format
msgid ""
"Invalid version string {version} from filename {filename}. Expected semantic "
"version format."
msgstr "Chaîne de version {version} non valide  à partir du nom de fichier {filename}. Format de version sémantique attendu."

#: app/api/utils.py:60
#, python-format
msgid "Expected namespace to be max length of %s"
msgstr "L'espace de nom attendu est d'une longueur maximale de %s"

#: app/api/utils.py:62
#, python-format
msgid "Expected name to be max length of %s"
msgstr "Le nom doit avoir une longueur maximale de %s"

#: app/api/utils.py:64
#, python-format
msgid "Expected version to be max length of %s"
msgstr "La version attendue est d'une longueur maximale de %s"

#: app/api/v3/serializers/namespace.py:67
#, python-format
msgid "'%s' is not a valid url."
msgstr "\"%s\" n'est pas un choix valide."

#: app/api/v3/serializers/namespace.py:100
msgid "Attribute 'name' is required"
msgstr "L'attribut \"nom\" est obligatoire"

#: app/api/v3/serializers/namespace.py:103
msgid "Name can only contain lower case letters, underscores and numbers"
msgstr "Le nom ne peut contenir que des lettres minuscules, des caractères de soulignement et des chiffres"

#: app/api/v3/serializers/namespace.py:106
msgid "Name must be longer than 2 characters"
msgstr "Le nom doit comporter plus de 2 caractères"

#: app/api/v3/serializers/namespace.py:109
msgid "Name cannot begin with '_'"
msgstr "Le nom ne peut pas commencer par '_'"

#: app/api/v3/serializers/sync.py:67
msgid "Password for proxy authentication."
msgstr "Mot de passe pour l'authentification du proxy."

#: app/api/v3/serializers/sync.py:74
msgid "User for proxy authentication."
msgstr "Utilisateur pour l'authentification du proxy."

#: app/api/v3/serializers/sync.py:87
msgid "Remote password."
msgstr "Mot de passe utilisateur à distance."

#: app/api/v3/serializers/sync.py:94
msgid "Remote user."
msgstr "Utilisateur distant."

#: app/api/v3/serializers/sync.py:148
msgid ""
"Syncing content from community domains without specifying a requirements "
"file is not allowed."
msgstr "La synchronisation du contenu des domaines communautaires sans spécifier un fichier d'exigences n'est pas autorisée."

#: app/api/v3/views/sync.py:45
msgid ""
"Syncing content from galaxy.ansible.com without specifying a requirements "
"file is not allowed."
msgstr "La synchronisation du contenu de galaxy.ansible.com sans spécifier un fichier d'exigences n'est pas autorisée."

#: app/api/v3/viewsets/collection.py:109
#, python-format
msgid "Path does not match: \"%s\""
msgstr "Le chemin ne correspond pas : \"%s\""

#: app/api/v3/viewsets/collection.py:130
#, python-brace-format
msgid "Namespace \"{0}\" does not exist."
msgstr "L'espace de nommage \"{0}\" n'existe pas."

#: app/api/v3/viewsets/collection.py:224
#, python-format
msgid "Unexpected response from content app. Code: %s."
msgstr "Réponse inattendue de l'application de contenu. Code :%s."

#: app/api/v3/viewsets/collection.py:254
#, python-format
msgid "Collection %s not found"
msgstr "Collection %s non trouvée"

#: app/api/v3/viewsets/collection.py:262
#, python-format
msgid "Repo(s) for moving collection %s not found"
msgstr "Repo(s) pour déplacer la collection %s non trouvé(s)"

#: app/api/v3/viewsets/collection.py:267
#, python-format
msgid "Collection %s not found in source repo"
msgstr "Collection %s non trouvée dans le repo source"

#: app/api/v3/viewsets/collection.py:270
#, python-format
msgid "Collection %s already found in destination repo"
msgstr "Collection %s déjà trouvée dans le repo de destination"

#: app/api/v3/viewsets/collection.py:296 app/tasks/publishing.py:103
#, python-format
msgid "Signing %s service not found"
msgstr "Le service de signature %s n’a pas été trouvé"

#: app/api/v3/viewsets/collection.py:306
#, python-brace-format
msgid ""
"Collection {namespace}.{name} could not be approved because system requires "
"at least a signature for approval."
msgstr "La collection {namespace}.{name} n'a pas pu être approuvée car le système exige au moins une signature pour l'approbation."

#: app/api/v3/viewsets/namespace.py:67
#, python-format
msgid "A namespace named %s already exists."
msgstr "Un espace de nom nommé %s existe déjà."

#: app/api/v3/viewsets/namespace.py:88
#, python-brace-format
msgid ""
"Namespace {name} cannot be deleted because there are still collections "
"associated with it."
msgstr "L'espace de nommage {name} ne peut pas être supprimé car des collections lui sont encore associées."

#: app/auth/keycloak.py:51
msgid "Authentication failed."
msgstr "Échec de notification."

#: app/exceptions.py:8
msgid "Data conflicts with existing entity."
msgstr "Les données entrent en conflit avec une entité existante."

#: app/tasks/index_registry.py:26
#, python-brace-format
msgid "Failed to create container {remote_name}. {error}"
msgstr "Créer un groupe de conteneurs {remote_name}. {error}"

#: app/tasks/index_registry.py:90
msgid ""
"A remote container with this name already exists, but is not associated with "
"any registry."
msgstr "Un conteneur distant portant ce nom existe déjà, mais n'est associé à aucun registre."

#: app/tasks/index_registry.py:97
msgid "A local container with this name already exists."
msgstr "Un conteneur local portant ce nom existe déjà."

#: app/tasks/publishing.py:57 app/tasks/publishing.py:94
#, python-format
msgid "Could not find staging repository: \"%s\""
msgstr "Impossible de trouver le référentiel «staging» : \"%s\""
